apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: todo-rabbitmq
  name: todo-rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: todo-rabbitmq
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: todo-rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: todo1234
            - name: RABBITMQ_DEFAULT_USER
              value: todo
          image: rabbitmq:3.13-management
          name: todo-rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          resources:
            limits:
              memory: "209715200"
      restartPolicy: Always
