apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml --replicas=2
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: todo-redis
  name: todo-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: todo-redis
